### ISSUE TITLE
Loading Bytecode error ?

### ISSUE THREAD

**Issue by ghost** [judovana/java-runtime-decompiler#255]
storing org.jrd.backend.communication.InstallDecompilerAgentImpl@3a87e0b3 {  id='8420', port=10900, host='localhost', addToBoot=false, setPolicy=false, props=',prop:com.redhat.decompiler.thermostat.port=10900', vm=sun.tools.attach.AttachProviderImpl@34ac9479: 8420, config=org.jrd.backend.data.Config@6ca0c0da, agentJar='C:/Users/anonymous/Desktop/runtime-decompiler-7.2-with-decompilers/libs/decompiler-agent-7.2.jar'}
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
        at org.jrd.backend.decompiling.PluginManager.decompile(PluginManager.java:203)
        at org.jrd.frontend.frame.main.decompilerview.DecompilationController.loadClassBytecode(DecompilationController.java:433)
        at org.jrd.frontend.frame.main.decompilerview.DecompilationController.lambda$new$10(DecompilationController.java:104)
        at org.jrd.frontend.frame.main.decompilerview.BytecodeDecompilerView$20.doInBackground(BytecodeDecompilerView.java:949)
        at org.jrd.frontend.frame.main.decompilerview.BytecodeDecompilerView$20.doInBackground(BytecodeDecompilerView.java:944)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 11 more

**Comment by JavaIsBadButBetterKotlin** [comment]
in the list of classes I get this error when I click
I'm using openjdk 11

**Comment by judovana** [comment]
It seems that on windows, the asm-tools are not on classpath.  The windows QA  is now missing :( 
You can see the full classpath in the star.bat Canyou verify it is correct and contains valid jars?

**Comment by judovana** [comment]
It seems it is no longer happening in 8.0. May you check?
